project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
      - 00_about.qmd
      - 00_setup.qmd
      - 01_data_import.qmd
      - 02_quality_control.qmd
      - 03_normalization.qmd
      - 04_pca_umap.qmd
      - 05_clustering.qmd
      - 06_ident_marker.qmd
      - 07_differential_expression_analysis.qmd
      - 08_enrichment_analysis.qmd
      - 09_202411_online_training_shared.qmd
      # - bioinformatics_update.qmd
      - sessioninfo.qmd
      - log.qmd

website:
  sidebar:
    style: "docked"
    title: "Single Cell Analysis with R - BD Rhapsody demo data"
    search: true
    page-navigation: true
    contents:
      - 00_about.qmd
      - 00_setup.qmd
      - 01_data_import.qmd
      - 02_quality_control.qmd
      - 03_normalization.qmd
      - 04_pca_umap.qmd
      - 05_clustering.qmd
      - 06_ident_marker.qmd
      - 07_differential_expression_analysis.qmd
      - 08_enrichment_analysis.qmd
      - 09_202411_online_training_shared.qmd
      # - bioinformatics_update.qmd
      - sessioninfo.qmd
      - log.qmd

format:
  html:
    code-link: true 
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    sidebar: true
    navbar: true

execute:
  freeze: false
  cache: false
  tidy: true

