project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  sidebar:
    style: "docked"
    title: "Single Cell Boot Camp: Analyzing Single Cell RNA-seq with R"
    search: true
    page-navigation: true
    contents:
      - index.qmd
      - setup.qmd
      - precourse_preparation_R.qmd
      - 01_data_import.qmd
      - 02_quality_control.qmd
      - 03_normalization.qmd
      - 04_clustering.qmd
      - 05_marker_identification.qmd
      - 06_differential_expression_analysis.qmd
      - 07_enrichment_analysis.qmd
      - supplementary_targeted_analysis.qmd
      - supplementary-gptcelltype.qmd
      - sessioninfo.qmd
      - log.qmd

format:
  html:
    code-link: true 
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true

execute:
  freeze: auto 
  cache: true
  tidy: true

