project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
      - 00_about.qmd
      - 00_setup.qmd
      - 01_data_import.qmd
      - 02_quality_control.qmd
      - 03_normalization.qmd
      - 04_pca_umap.qmd
      - 05_clustering.qmd
      - 06_ident_marker.qmd
      - 07_differential_expression_analysis.qmd
      - 08_enrichment_analysis.qmd
      - 09_202411_online_training_shared.qmd
      - 10_scRepertoire.qmd
      - 11_targeted_single_assay.qmd
      # - bioinformatics_update.qmd
      - sessioninfo.qmd
      - log.qmd

website:
  title: "Single Cell Analysis with R - BD Rhapsody"
  navbar:
    right:
      - icon: github
        href: https://github.com/analeigh-gui/single-cell-boot-camp
        aria-label: GitHub
  sidebar:
    style: "docked"
    search: true
    page-navigation: true
    contents:
      - 00_about.qmd
      - 00_setup.qmd
      - 01_data_import.qmd
      - 02_quality_control.qmd
      - 03_normalization.qmd
      - 04_pca_umap.qmd
      - 05_clustering.qmd
      - 06_ident_marker.qmd
      - 07_differential_expression_analysis.qmd
      - 08_enrichment_analysis.qmd
      - 09_202411_online_training_shared.qmd
      - 10_scRepertoire.qmd
      - 11_targeted_single_assay.qmd
      # - bioinformatics_update.qmd
      - sessioninfo.qmd
      - log.qmd

format:
  html:
    code-link: true 
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    sidebar: true
    navbar: true

execute:
  freeze: false
  cache: false
  tidy: true

